# golangci-lint configuration
# Based on https://github.com/maratori/golangci-lint-config

version: "2"

issues:
  max-same-issues: 50

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/tbhb/toolpaths-go)
        - blank
        - dot
        - alias
        - localmodule
      custom-order: true
    gofumpt:
      module-path: github.com/tbhb/toolpaths-go
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/tbhb/toolpaths-go
    golines:
      max-len: 120

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - iface
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0

    depguard:
      rules:
        "deprecated":
          files:
            - "$all"
          deny:
            - pkg: github.com/golang/protobuf
              desc: "Use google.golang.org/protobuf instead"
            - pkg: github.com/satori/go.uuid
              desc: "Use github.com/google/uuid instead"
            - pkg: github.com/gofrs/uuid$
              desc: "Use github.com/gofrs/uuid/v5 or later"
        "non-test files":
          files:
            - "!$test"
          deny:
            - pkg: math/rand$
              desc: "Use math/rand/v2 instead"
        "non-main files":
          files:
            - "!**/main.go"
          deny:
            - pkg: log$
              desc: "Use log/slog instead"

    errcheck:
      check-type-assertions: true

    exhaustive:
      check:
        - switch
        - map

    funlen:
      lines: 100
      statements: 50

    gochecksumtype:
      default-signifies-exhaustive: false

    gocognit:
      min-complexity: 20

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true

    mnd:
      ignored-functions:
        - args.Error
        - flag.Arg
        - flag.Duration.*
        - flag.Float.*
        - flag.Int.*
        - flag.Uint.*
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile

    nakedret:
      max-func-lines: 0

    nolintlint:
      allow-no-explanation: [funlen, gocognit, golines]
      require-explanation: true
      require-specific: true

    perfsprint:
      strconcat: false

    reassign:
      patterns:
        - ".*"

    sloglint:
      no-global: all
      context: scope

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1016
        - -QF1008

    usetesting:
      os-temp-dir: true

  exclusions:
    warn-unused: false
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - source: "TODO"
        linters: [godot]
      - text: "should have a package comment"
        linters: [revive]
      - text: 'exported \S+ \S+ should have comment( \(or a comment on this block\))? or be unexported'
        linters: [revive]
      - text: 'package comment should be of the form ".+"'
        source: "// ?(nolint|TODO)"
        linters: [revive]
      - text: 'comment on exported \S+ \S+ should be of the form ".+"'
        source: "// ?(nolint|TODO)"
        linters: [revive, staticcheck]
      - path: "_test\\.go"
        linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - noctx
